# reasons you might want to use `environment.yaml` instead of `requirements.txt`:
# - pip installs packages in a loop, without ensuring dependencies across all packages
#   are fulfilled simultaneously, but conda achieves proper dependency control across
#   all packages
# - conda allows for installing packages without requiring certain compilers or
#   libraries to be available in the system, since it installs precompiled binaries

name: das

channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

# it is strongly recommended to specify versions of packages installed through conda
# to avoid situation when version-unspecified packages install their latest major
# versions which can sometimes break things

# current approach below keeps the dependencies in the same major versions across all
# users, but allows for different minor and patch versions of packages where backwards
# compatibility is usually guaranteed

dependencies:
  - python=3.10
  - pytorch=2.*
  - torchvision
  - lightning=2.*
  - torchmetrics=0.*
  - cuda-version=12
  - hydra-core=1.*
  - rich=13.*
  - pre-commit=3.*
  - pytest=7.*
  # --------- loggers --------- #
  - wandb
  - ambertools # Required for MD generation
  #- openmm
  # - neptune-client
  # - mlflow
  # - comet-ml
  # - aim>=3.16.2 # no lower than 3.16.2, see https://github.com/aimhubio/aim/issues/2550

  - pip>=23
  - pip:
      - mdtraj
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils
      - normflows
      - nflows
      - einops
      - ipdb
      - torchsde
      - torchdiffeq
      - git+https://github.com/atong01/conditional-flow-matching.git
      - black
      - flake8
      - isort
      - jupyter-black
      - git+https://github.com/VincentStimper/resampled-base-flows.git # larsflow
      - git+https://github.com/atong01/bgflow.git
      - hydra-submitit-launcher
      - scikit-learn
      - scipy
      - matplotlib<3.10 #3.10 gives
      #AttributeError: 'FigureCanvasInterAgg' object has no attribute 'tostring_rgb'. Did you mean: 'tostring_argb'?
      - -e fab
      - -e runner/
      - deeptime
      # dit requires
      # --no-build-isolation flash-attn
      - huggingface_hub
      - torchtune
      - torchao
