# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: long
    cpus_per_task: 2
    mem_gb: 20
    gres: gpu:1
    timeout_min: 1440
    exclude: cn-g[001-012]
    array_parallelism: 10 # max num of tasks to run in parallel (via job array)
    setup:
      - "miniconda activate ${oc.env:MICROMAMBA_ENV}"
      - "unset CUDA_VISIBLE_DEVICES"
