  _target_: src.energies.multi_double_well_energy.MultiDoubleWellEnergy

  dimensionality: 8
  n_particles: 4
  data_path: "../data/dw4-dataidx.npy"

  device: ${trainer.accelerator}

  plot_samples_epoch_period: 1

  data_normalization_factor: 1.0

  is_molecule: true