_target_: src.energies.lennardjones_energy.LennardJonesEnergy
_partial_: true
dimensionality: 165
n_particles: 55
spatial_dim: 3
data_path: "../data/test_split_LJ55-1000-part1.npy"
data_path_train: "../data/train_split_LJ55-1000-part1.npy"
data_path_val: "../data/val_split_LJ55-1000-part1.npy"

plot_samples_epoch_period: 1

data_normalization_factor: 1.0

is_molecule: True

smooth: False
