# @package _global_

run_name: rdem_${logger.wandb.group}

logger:
  wandb:
    id: ${run_name}
    name: ${run_name}

hydra:
  run:
    dir: ${paths.log_dir}/${task_name}/runs/${run_name}
  sweep:
    dir: ${paths.log_dir}/${task_name}/multiruns/${run_name}

ckpt_path: ${paths.log_dir}/${task_name}/runs/${run_name}/checkpoints/last.ckpt

extras:
  # disable python warnings if they annoy you
  ignore_warnings: False

  # ask user for tags if none are provided in the config
  enforce_tags: True

  # pretty print config tree at the start of the run using Rich library
  print_config: True
