_target_: src.models.components.dit.DIT3D
_partial_: true
vocab_size: ${energy.spatial_dim}
n_particles: ${energy.n_particles}
#hidden_size: 512
hidden_size: 768
cond_dim: 128
#n_blocks: 4
#n_heads: 8
scale_by_sigma: True
dropout: 0.1
n_blocks: 12
n_heads: 12
