_target_: src.models.components.egnn_temp_conditioned.EGNN_dynamics
_partial_: true
n_particles: 13
n_dimension: 3
hidden_nf: 32
n_layers: 3
act_fn:
  _target_: torch.nn.SiLU
recurrent: True
tanh: True
attention: True
condition_time: True
condition_temperature: True
agg: "sum"
