_target_: src.models.components.mlp.MyMLPTemperature
_partial_: true
hidden_size: 128
hidden_layers: 3
emb_size: 128
time_emb: "sinusoidal"
input_emb: "sinusoidal"
input_dim: ${energy.dimensionality}
out_dim: ${energy.dimensionality}
