_target_: src.models.components.torchmd_net.TorchMDDynamics
_partial_: true
n_particles: ${energy.n_particles}
n_dimension: ${energy.spatial_dim}
hidden_nf: 32
n_layers: 6
n_heads: 1
is_alanine: True   
activation: "silu"
condition_time: True
condition_temperature: True
reduce_op: "sum"