# @package _global_
task_name: "debug_short"

model:
  num_integration_steps: 10
  num_negative_time_steps: 1

data:
  n_train_batches_per_epoch: 250

trainer:
  max_epochs: 1
  check_val_every_n_epoch: 1
