# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    account: aip-bengioy
    cpus_per_task: 8
    mem_gb: 24
    gres: gpu:1
    timeout_min: 2880
    array_parallelism: 10 # max num of tasks to run in parallel (via job array)
    setup:
      - "module purge"
      - "module load python/3.11 cuda/12.2"
      - "module load openmm/8.2.0"
      - "virtualenv --no-download $SLURM_TMPDIR/env"
      - "source $SLURM_TMPDIR/env/bin/activate"
      - "pip install --no-index --upgrade pip"
      - "pip install --no-index -r cc_requirements.txt"
      - "cd runner/"
      - "pip install -e ."
